/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dzm_ffmpeg_yinshipin_activity_FModActivity */

#ifndef _Included_com_dzm_ffmpeg_yinshipin_activity_FModActivity
#define _Included_com_dzm_ffmpeg_yinshipin_activity_FModActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_ORIGN
#define com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_ORIGN 0L
#undef com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_LOLI
#define com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_LOLI 1L
#undef com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_MAN
#define com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_MAN 2L
#undef com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_GOAST
#define com_dzm_ffmpeg_yinshipin_activity_FModActivity_MODE_GOAST 3L
/*
 * Class:     com_dzm_ffmpeg_yinshipin_activity_FModActivity
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_dzm_ffmpeg_yinshipin_activity_FModActivity_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
